### Numpy Library:-
Numpy is a Python Library used for working with arrays.
It also has functions for working on domain of linear algebra, fourier transform, and matrices etc.
Numpy stand for Numerical Python.

In [1]:
import numpy
arr = numpy.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [2]:
import numpy as np
arr1 = np.array([4, 5, 6, 7])
print(arr1)

[4 5 6 7]


In [3]:
# Now, we check its version.
print(np.__version__)

1.26.4


In [4]:
# Now, we check its type.
arr2 = ([32, 42, 53, 23])
print(arr2)
print(type(arr2))

[32, 42, 53, 23]
<class 'list'>


### Dimensions in Arrays:-
A dimenstion in arrays is one level of array depth (insted arrays).Nested Arrays: Nested arrays are arrays that have arrays as their elemetns.

In [10]:
# Create  a 0-D array.
arr3 = np.array(80)
print(arr3)

80


In [11]:
# Create a 1-D array.
arr4 = np.array([1, 2, 3, 4])
print(arr4)

[1 2 3 4]


In [12]:
# Create a 2-D array.
arr5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr5)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
# Create a 3-D array.
arr6 = np.array([[[9, 10, 11, 12], [13, 14, 15, 16]], [[17, 18, 19, 20], [21, 22, 23, 24]]])
print(arr6)

[[[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [16]:
# We can check the dimentions of arrays.
arr7 = np.array([[[9, 10, 11, 12], [13, 14, 15, 16]], [[17, 18, 19, 20], [21, 22, 23, 24]]])
print(arr7.ndim)

3


In [17]:
arr8 = np.array(30) # it means this is zero dimention array.
print(arr8.ndim)

0


In [18]:
arr9 = np.array([48, 29]) # 01 dimention array.
print(arr9.ndim)

1


### Hence, We can say that, array ma jetni suqare brackets ho ge otni he oski dimentions ho ge.

### Higher Dimentional Arrays:-
An array can have any number of dimentions. When the array is created, you can define the number of dimentions by using the ndmin argument.

In [21]:
# Create 10 Dimention Array.
arr10 = np.array([25, 26, 27, 28], ndmin = 10)
print(arr10)
# Now we can verify its dimentions as:
print(arr10.ndim)

[[[[[[[[[[25 26 27 28]]]]]]]]]]
10


### Access Array Elements:-
We can access the array element by its index number.

In [23]:
arr11 = np.array([29, 30, 31, 32])
print(arr11[0]) # here we access its first element. it means that indexing starts with zero (0).

29


In [25]:
# example to access the element in an array.
arr11 = np.array([33, 34, 35, 36])
print(arr11[2])

35


In [31]:
# Access the element on the first row, second column.
arr12 = np.array([[37, 38, 39, 40], [41, 42, 43, 44]])
print(arr12[0][1])

38


In [34]:
# Access the element on the second row, fourth column.
arr13 = np.array([[45, 46, 47, 48], [49, 50, 51, 52]])
print(arr13[1][3])

52


### We can add and also take square of elements in the array.

In [37]:
# Add
arr14 = ([1, 2, 3, 4])
print(arr14[1] + arr14[3])
arr15 = arr14[2]
arr16 = np.sqrt(arr15)
arr17 = arr15**2
print(arr16)
print(arr17)

6
1.7320508075688772
9


In [41]:
# Only Add
arr18 = ([1, 2, 3, 4])
print(arr18[1] + arr18[3]) # it means 2 + 4 = 6

6


In [3]:
import numpy as np
# Taking Square Root
arr19 = ([1, 2, 3, 4])
arr20 = arr19[1]
arr21 = np.sqrt(arr20)
print(arr21)
# now,
arr22 = arr20**2
print(arr22)

1.4142135623730951
4


### Slicing:-
We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step].

In [6]:
#Examples:
arr23 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr23[1:5]) # Slicing the elements from index 1 to 5.

[2 3 4 5]


In [8]:
# 2-D Array Example.
# From the second row, slice elements from index 1 to index 4 (In slicing last one index is not included).
arr24 = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(arr24[1, 1:4]) 

[17 18]


In [17]:
# 3-D Array Example.
arr25 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
print(arr25[1][0][3])
print(arr25.ndim)

12
3


### Data Types in NumPy.
Checking the Data Type of an Array. 
The NumPy array object has a property
called dtype that returns the data typ 
of the ar.ray

In [18]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [19]:
arr1 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
print(arr1)
print(arr1.dtype)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
int32


### Change Data Type:

In [26]:
# Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


### Shape of an Array:
The shape of an array is the number of elements in each dimension.

In [39]:
# Example: 2-D Array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) # here, 2 rows and 4 column.
print(arr.shape) 
print(arr.ndim)

(2, 4)
2


### Re-Shape of an Array:

In [44]:
A = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(A)
new_A = A.reshape(2,6) # It means 2 rows and 6 columns.
print(new_A)
print(A.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
1


A = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(A)
new_A = A.reshape(3,4) # It means 3 rows and 4 columns.
print(new_A)
print(A.ndim)

### Copy & View:-
Copy ma kisi ak array ko copy krty hn or new ma save krty hn.
View ma hum original array ko print krty hn.

In [47]:
arr = np.array([10,12,13,14,15,16,17,18]) 
print(arr.reshape(2,4).base) #View
B = ([10,12,13,14,15,16,17,18]) 
print(B) #Copy

[10 12 13 14 15 16 17 18]
[10, 12, 13, 14, 15, 16, 17, 18]


### Iteration:-
In Iteration we use For loop.

In [50]:
C = np.array([1,2,3,4])
for x in C:
    print(x)

1
2
3
4


### Structure Querry Language (SQL):

In [51]:
arr1 = np.array([[10, 12], [13, 14]])
arr2 = np.array([[15, 16], [17, 18]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[10 12 15 16]
 [13 14 17 18]]


In [52]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### Split Arrays.

In [53]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
newarr = np.array_split(arr,1.8)
print(newarr)
print(arr.dtype)

[array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])]
int32


### Searching Arrays:- 
We use the word "where" when we searching in numpy.

In [54]:
J = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9])
k = np.where(J%2==0)
print(k)

(array([1, 3, 5, 7], dtype=int64),)


### Filtering:- 
By using Boolean indices (Jo chz hmary pass True ho ge osko output ma dy ga).

In [55]:
K = np.array([1, 2, 3, 4, 5, 6, 7])
x = [False, True, False, True, False, True, False]
L = K[x]
print(L)

[2 4 6]
